login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.login, name='firstlogin'),
    path('trylogin', views.trylogin, name='tryLogin'),
    path('tryregister', views.tryregister, name='tryRegister'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout')
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'
urlpatterns = [
    path('browse', views.browse, name='browse'),
    path('write', views.write, name='write'),
    path('submit', views.submit, name='submit'),
    path('search', views.search, name='search'),
    path('read/<int:id_number>', views.read, name='read'),
    path('extend/<int:id_number>', views.extend, name='extend'),
    path('add', views.add, name='add'),
    path('mystories', views.mystories, name='mystories'),
    path('change', views.change, name='change'),
    path('delete/<int:id_number>', views.delete, name='delete'),
]

mod151_Nihal_SinghSingh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('menu/', include('menu.urls')),
]

login/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=255)

menu/models.py
from django.db import models
from login.models import User

# Create your models here.


class Story(models.Model):
    title = models.CharField(max_length=20)
    category = models.CharField(max_length=20)
    story = models.CharField(max_length=2000)
    fk_user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_beginning = models.BooleanField()

    def __str__(self):
        return self.title


class Extension(models.Model):
    fk_origin = models.ForeignKey(Story, on_delete=models.CASCADE, related_name='origin')
    fk_continuation = models.ForeignKey(Story, on_delete=models.CASCADE, related_name='continuation')

login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import User
from django.urls import reverse
from passlib.hash import pbkdf2_sha256

# Create your views here.


def login(request, has_account=1):
    return render(request, 'login.html', {'hasAccount': has_account})


def register(request, has_account=0):
    return render(request, 'login.html', {'hasAccount': has_account})


def trylogin(request):
    login_name = request.POST['login_name']
    login_password = request.POST['login_password']
    try:
        user_data = User.objects.get(username=login_name)
    except(KeyError, User.DoesNotExist):
        return render(request, 'login.html', {
            'error_message': "Your password or username is incorrect",
            'hasAccount': 1,
            'login_name': login_name,
            'login_password': login_password
        })
    else:
        if pbkdf2_sha256.verify(login_password, user_data.password):
            request.session['IsLoggedIn'] = True
            request.session['username'] = login_name
            request.session.set_expiry(0)
            return HttpResponseRedirect(reverse('menu:browse'))
        else:
            return render(request, 'login.html', {
                'error_message': "Your password or username is incorrect",
                'hasAccount': 1,
                'login_name': login_name,
                'login_password': login_password
            })


def tryregister(request):
    login_name = request.POST['login_name']
    login_password = request.POST['login_password']
    try:
        user_data = User.objects.get(username=login_name)
    except(KeyError, User.DoesNotExist):
        if len(login_name) > 0 and len(login_password) > 0:
            enc_password = pbkdf2_sha256.encrypt(login_password, rounds=12000, salt_size=32)
            new_entry = User(username=login_name, password=enc_password)
            new_entry.save()
            return HttpResponseRedirect(reverse('login:login'))
        else:
            return render(request, 'login.html', {
                'error_message': "Please give in a username and password",
                'hasAccount': 0,
                'login_name': login_name,
                'login_password': login_password
            })
    else:
        return render(request, 'login.html', {
            'error_message': "That username already exists",
            'hasAccount': 0,
            'login_name': login_name,
            'login_password': login_password
        })


def logout(request):
    request.session.delete()
    return login(request, 1)

menu/views.py
from django.shortcuts import render
from .models import Story, Extension
from login.models import User
from django.db.models import Q

# Create your views here.


def check(request):
    return render(request, 'login.html', {
        'error_message': "Please login",
        'hasAccount': 1
    })


def browse(request):
    if request.session.get('IsLoggedIn', False):
        stories = Story.objects.filter(is_beginning=True)
        return render(request, 'browse.html', {
            "stories": stories
        })
    else:
        return check(request)


def write(request):
    if request.session.get('IsLoggedIn', False):
        return render(request, 'write.html')
    else:
        return check(request)


def submit(request):
    if request.session.get('IsLoggedIn', False):
        title = request.POST['title']
        category = request.POST['category']
        story = request.POST['story']
        user = User.objects.get(username=request.session['username'])
        new_entry = Story(title=title, category=category, story=story, fk_user=user, is_beginning=True)
        new_entry.save()
        return read(request, new_entry.pk)
    else:
        return check(request)


def search(request):
    if request.session.get('IsLoggedIn', False):
        stories = Story.objects.filter(
            Q(is_beginning=True),
            Q(title__icontains=request.POST['story_name']) | Q(category__iexact=request.POST['story_name'])
        )
        return render(request, 'browse.html', {
            "stories": stories
        })
    else:
        return check(request)


def read(request, id_number):
    if request.session.get('IsLoggedIn', False):
        story = Story.objects.get(id=id_number)
        extensions = Extension.objects.filter(fk_origin=story)
        return render(request, 'read.html', {
            'title': story.title,
            'story': story.story,
            'id': id_number,
            'extensions': extensions,
        })
    else:
        return check(request)


def extend(request, id_number):
    if request.session.get('IsLoggedIn', False):
        story = Story.objects.get(id=id_number)
        return render(request, 'extend.html', {
            'story_id': id_number,
            'title': story.title,
        })
    else:
        return check(request)


def add(request):
    if request.session.get('IsLoggedIn', False):
        title = request.POST['link_title']
        old_story = Story.objects.get(id=request.POST['id_story'].split(':')[0])
        category = old_story.category
        story = request.POST['story']
        user = User.objects.get(username=request.session['username'])
        new_story = Story(title=title, category=category, story=story, fk_user=user, is_beginning=False)
        new_story.save()
        new_entry = Extension(fk_origin=old_story, fk_continuation=new_story)
        new_entry.save()
        return read(request, new_story.pk)
    else:
        return check(request)


def mystories(request):
    if request.session.get('IsLoggedIn', False):
        stories = Story.objects.filter(fk_user__username=request.session['username']).order_by('title')
        return render(request, 'mystories.html', {
            "stories": stories
        })
    else:
        return check(request)


def change(request):
    if request.session.get('IsLoggedIn', False):
        old_story = Story.objects.get(id=request.POST['old_title'].split('.')[0])
        if len(request.POST['title']) > 0:
            old_story.title = request.POST['title']
        if len(request.POST['category']) > 0:
            old_story.category = request.POST['category']
        if len(request.POST['story']) > 0:
            old_story.story = request.POST['story']
        old_story.save()
        return mystories(request)
    else:
        return check(request)


def delete(request, id_number):
    if request.session.get('IsLoggedIn', False):
        story = Story.objects.get(id=id_number)
        story.delete()
        return mystories(request)
    else:
        return check(request)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block links %}{% endblock %}
</head>
<body>
<div id="header">
    <div id="icons">
        {% load static %}
        <img id="logo" src="{% static 'Logo.png' %}" alt="Write stuff">
        <p></p>
    </div>
    <div id="navbar">
        <a class="tab" href="{% url 'menu:browse' %}">Browse</a>
        <a class="tab" href="{% url 'menu:write' %}">Write</a>
        <a class="tab" href="{% url 'menu:mystories' %}">My stories</a>
        <a class="tab" href="{% url 'login:logout' %}">Logout</a>
    </div>
</div>
{% block content %}{% endblock %}
</body>
</html>

templates/browse.html
{% extends "base.html" %}
{% block title %}Browse{% endblock %}
{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'browsestyle.css' %}">
{% endblock %}
{% block content %}
    <form id="search" method="post" action="{% url 'menu:search' %}">
        {% csrf_token %}
        <input id="story_name" type="text" name="story_name" required>
        <input id="submit" type="submit" value="Search">
    </form>
    <div id="list">
        {% for story in stories %}
            <a href="{% url "menu:read" story.pk %}" class="results">
                <h1>{{ story.title }}</h1>
                <pre>Kategorie:{{ story.category }}   Autor:{{ story.fk_user.username }}   Likes:0</pre>
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/extend.html
{% extends "base.html" %}

{% block title %}Extend{% endblock %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'browsestyle.css' %}">
    <link rel="stylesheet" href="{% static 'writestyle.css' %}">
{% endblock %}

{% block content %}
    <form id="extend" method="post" action="{% url 'menu:add' %}">{% csrf_token %}
        <div>
            <h3>Previous story</h3>
            <input id="id_story" type="text" name="id_story" required readonly value="{{ story_id }}: {{ title }}">
        </div>
        <div>
            <h3>Link title</h3>
            <input id="link_title" type="text" name="link_title" maxlength="20" required>
        </div>
        <div>
            <h3>Story</h3>
            <textarea form="extend" id="story" name="story" maxlength="1600" minlength="100" required></textarea>
        </div>
        <input id="submit" type="submit" value="Submit">
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'loginstyle.css' %}">
    <title>Login screen</title>
</head>
<body>
<div id="login">
    <h1>
        {% if hasAccount == 1 %}
            Login
        {% else %}
            Register
        {% endif %}
    </h1>
    {% if error_message %}
        <p id="error"><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form id="login_form" method="post"
          action= {% if hasAccount == 1 %} "{% url 'login:tryLogin' %}" {% else %}"{% url 'login:tryRegister' %}
              "{% endif %}
    >
    {% csrf_token %}
    <p>Please enter your username</p>
    <input type="text" class="field" name="login_name" value={{ login_name }}>
    <p>Please enter your password</p>
    <input type="password" class="field" name="login_password" value={{ login_password }}>
    <input id="login_button" type="submit" {% if hasAccount == 1 %} value="Login"
           {% else %}value="Register" {% endif %}>
    {% if hasAccount == 1 %}
        <a href="{% url 'login:register' %}" id="register_link">New user?</a>
    {% else %}
        <a href="{% url 'login:login' %}" id="register_link">Go back to login</a>
    {% endif %}
    </form>
</div>
</body>
</html>

templates/mystories.html
{% extends "base.html" %}

{% block title %}Browse{% endblock %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'browsestyle.css' %}">
    <link rel="stylesheet" href="{% static 'mystoriesstyle.css' %}">
{% endblock %}

{% block content %}
    <div id="list">
        {% for story in stories %}
            <div class="my_stories">
                <div>
                    <a href="{% url "menu:read" story.pk %}" style="color: black; text-decoration: none">
                        <h1>{{ story.title }}</h1>
                        <pre>Kategorie:{{ story.category }}   Autor:{{ story.fk_user.username }}   Likes:0</pre>
                    </a>
                </div>
                <div class="button_section">
                    <button onclick="openPopup({{ story.pk }}, `{{ story.title }}`)">Change</button>
                    <button onclick="openPrompt('{% url 'menu:delete' story.pk %}')">Delete</button>
                </div>
            </div>
        {% endfor %}
    </div>

    <div id="change">
        <form id="form" method="post" action="{% url 'menu:change' %}">{% csrf_token %}
            <div>
                <input type="text" name="old_title" id="old_title" readonly/>
            </div>
            <div>
                <h3>New title</h3>
                <input id="title" type="text" name="title" maxlength="20"
                       placeholder="Leave this to empty to not change it">
            </div>
            <div>
                <h3>New category</h3>
                <select name="category" id="category">
                    <option value="Fiction">Science fiction</option>
                    <option value="Fantasy">Fantasy</option>
                    <option value="Comedy">Comedy</option>
                    <option value="Romance">Romance</option>
                    <option value="Horror">Horror</option>
                </select>
            </div>
            <div id="big_div">
                <h3>New story</h3>
                <textarea form="form" id="story" name="story" maxlength="1800" minlength="100"
                          placeholder="Leave this to empty to not change it"></textarea>
            </div>
            <div class="button_section">
                <input class="button" type="submit" value="Submit">
                <div class="button" onclick="closePopup()">Cancel</div>
            </div>
        </form>
    </div>

    <script src="../static/mystoriesscript.js"></script>
{% endblock %}

templates/read.html
{% extends "base.html" %}

{% block title %}Read{% endblock %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'browsestyle.css' %}">
    <link rel="stylesheet" href="{% static 'readstyle.css' %}">
{% endblock %}

{% block content %}
    <div id="read">
        <h1>{{ title }}</h1>
        <pre id="text">{{ story }}</pre>
    </div>
    {% for extension in extensions %}
        <a class="extend"
           href="{% url 'menu:read' extension.fk_continuation.pk %}">{{ extension.fk_continuation.title }}</a>
    {% endfor %}
    <a class="extend" href="{% url 'menu:extend' id %}">Extend this story</a>
{% endblock %}

templates/write.html
{% extends "base.html" %}
{% block title %}Write{% endblock %}
{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'browsestyle.css' %}">
    <link rel="stylesheet" href="{% static 'writestyle.css' %}">
{% endblock %}
{% block content %}
    <form id="write" method="post" action="{% url 'menu:submit' %}">{% csrf_token %}
        <div>
            <h3>Title</h3>
            <input id="title" type="text" name="title" maxlength="20" required>
        </div>
        <div>
            <h3>Category</h3>
            <select name="category" id="category" required>
                <option value="Fiction">Science fiction</option>
                <option value="Fantasy">Fantasy</option>
                <option value="Comedy">Comedy</option>
                <option value="Romance">Romance</option>
                <option value="Horror">Horror</option>
            </select>
        </div>
        <div>
            <h3>Story</h3>
            <textarea form="write" id="story" name="story" maxlength="1800" minlength="100" required></textarea>
        </div>
        <input id="submit" type="submit" value="Submit">
    </form>
{% endblock %}